modLoader = "javafml"
loaderVersion = "[4,)"
license = "GPL-3.0"

[[mixins]]
config = "townstead.mixins.json"

[[mods]]
modId = "townstead"
version = "${version}"
displayName = "Townstead"
authors = "AetherianArtificer"
description = '''A full expansion for MCA Reborn â€” starting with villager hunger.'''

[[dependencies.townstead]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.townstead]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.22)"
ordering = "NONE"
side = "BOTH"

[[dependencies.townstead]]
modId = "mca"
type = "required"
versionRange = "[7.7.0,)"
ordering = "AFTER"
side = "BOTH"
